const BCS_DATA = {
  "week": "2025-09-21",
  "rows": [
    {
      "team": "Ohio State",
      "bcs_score": 0.940832,
      "computers": 0.84,
      "ap_pct": 0.987273,
      "coaches_pct": 0.995224,
      "comp_inputs_used": 4,
      "ap_rank": 1,
      "coaches_rank": 1,
      "rank": 1,
      "comp_rank": "T1"
    },
    {
      "team": "Georgia",
      "bcs_score": 0.864779,
      "computers": 0.84,
      "ap_pct": 0.860606,
      "coaches_pct": 0.893731,
      "comp_inputs_used": 4,
      "ap_rank": 5,
      "coaches_rank": 3,
      "rank": 2,
      "comp_rank": "T1"
    },
    {
      "team": "Miami",
      "bcs_score": 0.827196,
      "computers": 0.75,
      "ap_pct": 0.896364,
      "coaches_pct": 0.835224,
      "comp_inputs_used": 4,
      "ap_rank": 2,
      "coaches_rank": 6,
      "rank": 3,
      "comp_rank": "4"
    },
    {
      "team": "LSU",
      "bcs_score": 0.826311,
      "computers": 0.74,
      "ap_pct": 0.868485,
      "coaches_pct": 0.870448,
      "comp_inputs_used": 4,
      "ap_rank": 4,
      "coaches_rank": 4,
      "rank": 4,
      "comp_rank": "5"
    },
    {
      "team": "Penn State",
      "bcs_score": 0.813805,
      "computers": 0.63,
      "ap_pct": 0.884848,
      "coaches_pct": 0.926567,
      "comp_inputs_used": 4,
      "ap_rank": 3,
      "coaches_rank": 2,
      "rank": 5,
      "comp_rank": "9"
    },
    {
      "team": "Oregon",
      "bcs_score": 0.777268,
      "computers": 0.62,
      "ap_pct": 0.850909,
      "coaches_pct": 0.860896,
      "comp_inputs_used": 4,
      "ap_rank": 6,
      "coaches_rank": 5,
      "rank": 6,
      "comp_rank": "10"
    },
    {
      "team": "Oklahoma",
      "bcs_score": 0.684993,
      "computers": 0.72,
      "ap_pct": 0.723636,
      "coaches_pct": 0.611343,
      "comp_inputs_used": 4,
      "ap_rank": 7,
      "coaches_rank": 10,
      "rank": 7,
      "comp_rank": "6"
    },
    {
      "team": "Texas A&M",
      "bcs_score": 0.657461,
      "computers": 0.7,
      "ap_pct": 0.649697,
      "coaches_pct": 0.622687,
      "comp_inputs_used": 4,
      "ap_rank": 9,
      "coaches_rank": 9,
      "rank": 8,
      "comp_rank": "7"
    },
    {
      "team": "Texas",
      "bcs_score": 0.650799,
      "computers": 0.59,
      "ap_pct": 0.640606,
      "coaches_pct": 0.721791,
      "comp_inputs_used": 4,
      "ap_rank": 10,
      "coaches_rank": 7,
      "rank": 9,
      "comp_rank": "11"
    },
    {
      "team": "Ole Miss",
      "bcs_score": 0.648512,
      "computers": 0.84,
      "ap_pct": 0.510909,
      "coaches_pct": 0.594627,
      "comp_inputs_used": 4,
      "ap_rank": 13,
      "coaches_rank": 11,
      "rank": 10,
      "comp_rank": "T1"
    },
    {
      "team": "Indiana",
      "bcs_score": 0.605423,
      "computers": 0.67,
      "ap_pct": 0.6,
      "coaches_pct": 0.546269,
      "comp_inputs_used": 4,
      "ap_rank": 11,
      "coaches_rank": 12,
      "rank": 11,
      "comp_rank": "8"
    },
    {
      "team": "Florida State",
      "bcs_score": 0.487895,
      "computers": 0.09,
      "ap_pct": 0.71697,
      "coaches_pct": 0.656716,
      "comp_inputs_used": 4,
      "ap_rank": 8,
      "coaches_rank": 8,
      "rank": 12,
      "comp_rank": "T33"
    },
    {
      "team": "Texas Tech",
      "bcs_score": 0.447062,
      "computers": 0.32,
      "ap_pct": 0.539394,
      "coaches_pct": 0.481791,
      "comp_inputs_used": 4,
      "ap_rank": 12,
      "coaches_rank": 14,
      "rank": 13,
      "comp_rank": "16"
    },
    {
      "team": "Iowa State",
      "bcs_score": 0.427175,
      "computers": 0.29,
      "ap_pct": 0.472121,
      "coaches_pct": 0.519403,
      "comp_inputs_used": 4,
      "ap_rank": 14,
      "coaches_rank": 13,
      "rank": 14,
      "comp_rank": "T17"
    },
    {
      "team": "Alabama",
      "bcs_score": 0.399356,
      "computers": 0.45,
      "ap_pct": 0.360606,
      "coaches_pct": 0.387463,
      "comp_inputs_used": 4,
      "ap_rank": 17,
      "coaches_rank": 16,
      "rank": 15,
      "comp_rank": "14"
    },
    {
      "team": "Tennessee",
      "bcs_score": 0.360571,
      "computers": 0.27,
      "ap_pct": 0.384848,
      "coaches_pct": 0.426866,
      "comp_inputs_used": 4,
      "ap_rank": 15,
      "coaches_rank": 15,
      "rank": 16,
      "comp_rank": "19"
    },
    {
      "team": "Missouri",
      "bcs_score": 0.350816,
      "computers": 0.52,
      "ap_pct": 0.273939,
      "coaches_pct": 0.258507,
      "comp_inputs_used": 4,
      "ap_rank": 20,
      "coaches_rank": 19,
      "rank": 17,
      "comp_rank": "13"
    },
    {
      "team": "Michigan",
      "bcs_score": 0.312525,
      "computers": 0.38,
      "ap_pct": 0.277576,
      "coaches_pct": 0.28,
      "comp_inputs_used": 4,
      "ap_rank": 19,
      "coaches_rank": 18,
      "rank": 18,
      "comp_rank": "15"
    },
    {
      "team": "Georgia Tech",
      "bcs_score": 0.305186,
      "computers": 0.22,
      "ap_pct": 0.362424,
      "coaches_pct": 0.333134,
      "comp_inputs_used": 4,
      "ap_rank": 16,
      "coaches_rank": 17,
      "rank": 19,
      "comp_rank": "20"
    },
    {
      "team": "USC",
      "bcs_score": 0.293997,
      "computers": 0.573333,
      "ap_pct": 0.16,
      "coaches_pct": 0.148657,
      "comp_inputs_used": 3,
      "ap_rank": 21,
      "coaches_rank": 22,
      "rank": 20,
      "comp_rank": "12"
    },
    {
      "team": "Vanderbilt",
      "bcs_score": 0.259955,
      "computers": 0.2,
      "ap_pct": 0.330909,
      "coaches_pct": 0.248955,
      "comp_inputs_used": 4,
      "ap_rank": 18,
      "coaches_rank": 20,
      "rank": 21,
      "comp_rank": "22"
    },
    {
      "team": "Notre Dame",
      "bcs_score": 0.192849,
      "computers": 0.29,
      "ap_pct": 0.132727,
      "coaches_pct": 0.155821,
      "comp_inputs_used": 4,
      "ap_rank": 22,
      "coaches_rank": 21,
      "rank": 22,
      "comp_rank": "T17"
    },
    {
      "team": "Illinois",
      "bcs_score": 0.105213,
      "computers": 0.1,
      "ap_pct": 0.087879,
      "coaches_pct": 0.127761,
      "comp_inputs_used": 4,
      "ap_rank": 23,
      "coaches_rank": 23,
      "rank": 23,
      "comp_rank": "T30"
    },
    {
      "team": "TCU",
      "bcs_score": 0.086834,
      "computers": 0.11,
      "ap_pct": 0.083636,
      "coaches_pct": 0.066866,
      "comp_inputs_used": 4,
      "ap_rank": 24,
      "coaches_rank": 25,
      "rank": 24,
      "comp_rank": "T28"
    },
    {
      "team": "BYU",
      "bcs_score": 0.083281,
      "computers": 0.06,
      "ap_pct": 0.079394,
      "coaches_pct": 0.110448,
      "comp_inputs_used": 4,
      "ap_rank": 25,
      "coaches_rank": 24,
      "rank": 25,
      "comp_rank": "35"
    },
    {
      "team": "Mississippi State",
      "bcs_score": 0.07,
      "computers": 0.21,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 26,
      "comp_rank": "21"
    },
    {
      "team": "Auburn",
      "bcs_score": 0.06,
      "computers": 0.18,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 27,
      "comp_rank": "23"
    },
    {
      "team": "Memphis",
      "bcs_score": 0.046667,
      "computers": 0.14,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 28,
      "comp_rank": "24"
    },
    {
      "team": "North Texas",
      "bcs_score": 0.043333,
      "computers": 0.13,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 29,
      "comp_rank": "25"
    },
    {
      "team": "Washington",
      "bcs_score": 0.04,
      "computers": 0.12,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 30,
      "comp_rank": "T26"
    },
    {
      "team": "Houston",
      "bcs_score": 0.04,
      "computers": 0.12,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 31,
      "comp_rank": "T26"
    },
    {
      "team": "Louisville",
      "bcs_score": 0.036667,
      "computers": 0.11,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 32,
      "comp_rank": "T28"
    },
    {
      "team": "Maryland",
      "bcs_score": 0.033333,
      "computers": 0.1,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 33,
      "comp_rank": "T30"
    },
    {
      "team": "Arizona State",
      "bcs_score": 0.033333,
      "computers": 0.1,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 34,
      "comp_rank": "T30"
    },
    {
      "team": "Florida",
      "bcs_score": 0.03,
      "computers": 0.09,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 35,
      "comp_rank": "T33"
    },
    {
      "team": "UCF",
      "bcs_score": 0.016667,
      "computers": 0.05,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 36,
      "comp_rank": "36"
    },
    {
      "team": "Clemson",
      "bcs_score": 0.006667,
      "computers": 0.02,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 37,
      "comp_rank": "37"
    },
    {
      "team": "South Florida",
      "bcs_score": 0.003333,
      "computers": 0.01,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 38,
      "comp_rank": "38"
    },
    {
      "team": "Wyoming",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 39,
      "comp_rank": "T39"
    },
    {
      "team": "Wisconsin",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 40,
      "comp_rank": "T39"
    },
    {
      "team": "Western Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 41,
      "comp_rank": "T39"
    },
    {
      "team": "Western Kentucky",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 42,
      "comp_rank": "T39"
    },
    {
      "team": "West Virginia",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 43,
      "comp_rank": "T39"
    },
    {
      "team": "West Kentucky",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 44,
      "comp_rank": "T39"
    },
    {
      "team": "Washington State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 45,
      "comp_rank": "T39"
    },
    {
      "team": "Washington St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 46,
      "comp_rank": "T39"
    },
    {
      "team": "Wake Forest",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 47,
      "comp_rank": "T39"
    },
    {
      "team": "W Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 48,
      "comp_rank": "T39"
    },
    {
      "team": "Virginia Tech",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 49,
      "comp_rank": "T39"
    },
    {
      "team": "Virginia",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 50,
      "comp_rank": "T39"
    },
    {
      "team": "Utah State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 51,
      "comp_rank": "T39"
    },
    {
      "team": "Utah St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 52,
      "comp_rank": "T39"
    },
    {
      "team": "Utah",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 53,
      "comp_rank": "T39"
    },
    {
      "team": "UTSA",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 54,
      "comp_rank": "T39"
    },
    {
      "team": "UTEP",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 55,
      "comp_rank": "T39"
    },
    {
      "team": "UNLV",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 56,
      "comp_rank": "T39"
    },
    {
      "team": "UCLA",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 57,
      "comp_rank": "T39"
    },
    {
      "team": "UAB",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 58,
      "comp_rank": "T39"
    },
    {
      "team": "Tulsa",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 59,
      "comp_rank": "T39"
    },
    {
      "team": "Tulane",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 60,
      "comp_rank": "T39"
    },
    {
      "team": "Troy",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 61,
      "comp_rank": "T39"
    },
    {
      "team": "Toledo",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 62,
      "comp_rank": "T39"
    },
    {
      "team": "Texas-El Paso",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 63,
      "comp_rank": "T39"
    },
    {
      "team": "Texas State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 64,
      "comp_rank": "T39"
    },
    {
      "team": "Texas St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 65,
      "comp_rank": "T39"
    },
    {
      "team": "Temple",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 66,
      "comp_rank": "T39"
    },
    {
      "team": "Syracuse",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 67,
      "comp_rank": "T39"
    },
    {
      "team": "Stanford",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 68,
      "comp_rank": "T39"
    },
    {
      "team": "Southern Miss",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 69,
      "comp_rank": "T39"
    },
    {
      "team": "Southern Cal",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 70,
      "comp_rank": "T39"
    },
    {
      "team": "South Carolina",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 71,
      "comp_rank": "T39"
    },
    {
      "team": "South Alabama",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 72,
      "comp_rank": "T39"
    },
    {
      "team": "San Jose State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 73,
      "comp_rank": "T39"
    },
    {
      "team": "San Jose St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 74,
      "comp_rank": "T39"
    },
    {
      "team": "San Diego State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 75,
      "comp_rank": "T39"
    },
    {
      "team": "San Diego St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 76,
      "comp_rank": "T39"
    },
    {
      "team": "Sam Houston State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 77,
      "comp_rank": "T39"
    },
    {
      "team": "Sam Houston St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 78,
      "comp_rank": "T39"
    },
    {
      "team": "Sam Houston",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 79,
      "comp_rank": "T39"
    },
    {
      "team": "SMU",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 80,
      "comp_rank": "T39"
    },
    {
      "team": "Rutgers",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 81,
      "comp_rank": "T39"
    },
    {
      "team": "Rice",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 82,
      "comp_rank": "T39"
    },
    {
      "team": "Purdue",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 83,
      "comp_rank": "T39"
    },
    {
      "team": "Pitt",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 84,
      "comp_rank": "T39"
    },
    {
      "team": "Oregon State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 85,
      "comp_rank": "T39"
    },
    {
      "team": "Oregon St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 86,
      "comp_rank": "T39"
    },
    {
      "team": "Old Dominion",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 87,
      "comp_rank": "T39"
    },
    {
      "team": "Oklahoma State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 88,
      "comp_rank": "T39"
    },
    {
      "team": "Oklahoma St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 89,
      "comp_rank": "T39"
    },
    {
      "team": "Ohio",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 90,
      "comp_rank": "T39"
    },
    {
      "team": "Northwestern",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 91,
      "comp_rank": "T39"
    },
    {
      "team": "Northern Illinois",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 92,
      "comp_rank": "T39"
    },
    {
      "team": "North Carolina St.",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 93,
      "comp_rank": "T39"
    },
    {
      "team": "North Carolina",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 94,
      "comp_rank": "T39"
    },
    {
      "team": "New Mexico State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 95,
      "comp_rank": "T39"
    },
    {
      "team": "New Mexico St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 96,
      "comp_rank": "T39"
    },
    {
      "team": "New Mexico",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 97,
      "comp_rank": "T39"
    },
    {
      "team": "Nevada-Las Vegas",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 98,
      "comp_rank": "T39"
    },
    {
      "team": "Nevada",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 99,
      "comp_rank": "T39"
    },
    {
      "team": "Nebraska",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 100,
      "comp_rank": "T39"
    },
    {
      "team": "Navy",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 101,
      "comp_rank": "T39"
    },
    {
      "team": "NC State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 102,
      "comp_rank": "T39"
    },
    {
      "team": "Missouri State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 103,
      "comp_rank": "T39"
    },
    {
      "team": "Missouri St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 104,
      "comp_rank": "T39"
    },
    {
      "team": "Minnesota",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 105,
      "comp_rank": "T39"
    },
    {
      "team": "Middle Tennessee",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 106,
      "comp_rank": "T39"
    },
    {
      "team": "Middle Tenn St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 107,
      "comp_rank": "T39"
    },
    {
      "team": "Michigan State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 108,
      "comp_rank": "T39"
    },
    {
      "team": "Michigan St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 109,
      "comp_rank": "T39"
    },
    {
      "team": "Miami-Ohio",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 110,
      "comp_rank": "T39"
    },
    {
      "team": "Miami (Ohio)",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 111,
      "comp_rank": "T39"
    },
    {
      "team": "Miami (OH)",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 112,
      "comp_rank": "T39"
    },
    {
      "team": "Massachusetts",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 113,
      "comp_rank": "T39"
    },
    {
      "team": "Marshall",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 114,
      "comp_rank": "T39"
    },
    {
      "team": "Louisiana Tech",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 115,
      "comp_rank": "T39"
    },
    {
      "team": "Louisiana",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 116,
      "comp_rank": "T39"
    },
    {
      "team": "Liberty",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 117,
      "comp_rank": "T39"
    },
    {
      "team": "La. Monroe",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 118,
      "comp_rank": "T39"
    },
    {
      "team": "La. Lafayette",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 119,
      "comp_rank": "T39"
    },
    {
      "team": "LA Monroe",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 120,
      "comp_rank": "T39"
    },
    {
      "team": "LA Lafayette",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 121,
      "comp_rank": "T39"
    },
    {
      "team": "Kentucky",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 122,
      "comp_rank": "T39"
    },
    {
      "team": "Kent State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 123,
      "comp_rank": "T39"
    },
    {
      "team": "Kent St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 124,
      "comp_rank": "T39"
    },
    {
      "team": "Kennesaw State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 125,
      "comp_rank": "T39"
    },
    {
      "team": "Kansas State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 126,
      "comp_rank": "T39"
    },
    {
      "team": "Kansas St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 127,
      "comp_rank": "T39"
    },
    {
      "team": "Kansas",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 128,
      "comp_rank": "T39"
    },
    {
      "team": "James Madison",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 129,
      "comp_rank": "T39"
    },
    {
      "team": "Jacksonville State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 130,
      "comp_rank": "T39"
    },
    {
      "team": "Jacksonville St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 131,
      "comp_rank": "T39"
    },
    {
      "team": "Iowa",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 132,
      "comp_rank": "T39"
    },
    {
      "team": "Hawaii",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 133,
      "comp_rank": "T39"
    },
    {
      "team": "Georgia State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 134,
      "comp_rank": "T39"
    },
    {
      "team": "Georgia St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 135,
      "comp_rank": "T39"
    },
    {
      "team": "Georgia Southern",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 136,
      "comp_rank": "T39"
    },
    {
      "team": "Fresno State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 137,
      "comp_rank": "T39"
    },
    {
      "team": "Fresno St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 138,
      "comp_rank": "T39"
    },
    {
      "team": "Florida Intl",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 139,
      "comp_rank": "T39"
    },
    {
      "team": "Florida Atlantic",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 140,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 9",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 141,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 8",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 142,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 7",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 143,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 6",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 144,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 5",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 145,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 4",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 146,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 31",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 147,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 30",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 148,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 3",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 149,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 29",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 150,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 28",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 151,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 27",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 152,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 26",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 153,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 25",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 154,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 24",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 155,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 23",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 156,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 22",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 157,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 21",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 158,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 20",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 159,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 2",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 160,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 19",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 161,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 18",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 162,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 17",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 163,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 16",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 164,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 15",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 165,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 14",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 166,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 13",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 167,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 12",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 168,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 11",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 169,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 10",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 170,
      "comp_rank": "T39"
    },
    {
      "team": "FCS GROUP 1",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 171,
      "comp_rank": "T39"
    },
    {
      "team": "Eastern Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 172,
      "comp_rank": "T39"
    },
    {
      "team": "East Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 173,
      "comp_rank": "T39"
    },
    {
      "team": "East Carolina",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 174,
      "comp_rank": "T39"
    },
    {
      "team": "Duke",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 175,
      "comp_rank": "T39"
    },
    {
      "team": "Delaware",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 176,
      "comp_rank": "T39"
    },
    {
      "team": "Connecticut",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 177,
      "comp_rank": "T39"
    },
    {
      "team": "Colorado State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 178,
      "comp_rank": "T39"
    },
    {
      "team": "Colorado St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 179,
      "comp_rank": "T39"
    },
    {
      "team": "Colorado",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 180,
      "comp_rank": "T39"
    },
    {
      "team": "Coastal Carolina",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 181,
      "comp_rank": "T39"
    },
    {
      "team": "Cincinnati",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 182,
      "comp_rank": "T39"
    },
    {
      "team": "Charlotte",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 183,
      "comp_rank": "T39"
    },
    {
      "team": "Central Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 184,
      "comp_rank": "T39"
    },
    {
      "team": "Cent Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 185,
      "comp_rank": "T39"
    },
    {
      "team": "California",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 186,
      "comp_rank": "T39"
    },
    {
      "team": "Buffalo",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 187,
      "comp_rank": "T39"
    },
    {
      "team": "Bowling Green",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 188,
      "comp_rank": "T39"
    },
    {
      "team": "Boston College",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 189,
      "comp_rank": "T39"
    },
    {
      "team": "Boston Coll",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 190,
      "comp_rank": "T39"
    },
    {
      "team": "Boise State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 191,
      "comp_rank": "T39"
    },
    {
      "team": "Boise St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 192,
      "comp_rank": "T39"
    },
    {
      "team": "Baylor",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 193,
      "comp_rank": "T39"
    },
    {
      "team": "Ball State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 194,
      "comp_rank": "T39"
    },
    {
      "team": "Ball St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 195,
      "comp_rank": "T39"
    },
    {
      "team": "Army",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 196,
      "comp_rank": "T39"
    },
    {
      "team": "Arkansas State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 197,
      "comp_rank": "T39"
    },
    {
      "team": "Arkansas St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 198,
      "comp_rank": "T39"
    },
    {
      "team": "Arkansas",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 199,
      "comp_rank": "T39"
    },
    {
      "team": "Arizona St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 200,
      "comp_rank": "T39"
    },
    {
      "team": "Arizona",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 201,
      "comp_rank": "T39"
    },
    {
      "team": "Appalachian State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 202,
      "comp_rank": "T39"
    },
    {
      "team": "Appalachian St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 203,
      "comp_rank": "T39"
    },
    {
      "team": "Akron",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 204,
      "comp_rank": "T39"
    },
    {
      "team": "Air Force",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 205,
      "comp_rank": "T39"
    }
  ],
  "build_time": "2025-09-23T02:40:47Z",
  "source_week": "data/2025/week05"
};