const BCS_DATA = {
  "week": "2025-09-21",
  "rows": [
    {
      "team": "Ohio State",
      "bcs_score": 0.940832,
      "computers": 0.84,
      "ap_pct": 0.987273,
      "coaches_pct": 0.995224,
      "comp_inputs_used": 4,
      "comp_rank": 5,
      "ap_rank": 1,
      "coaches_rank": 1,
      "rank": 1
    },
    {
      "team": "Georgia",
      "bcs_score": 0.864779,
      "computers": 0.84,
      "ap_pct": 0.860606,
      "coaches_pct": 0.893731,
      "comp_inputs_used": 4,
      "comp_rank": 5,
      "ap_rank": 5,
      "coaches_rank": 3,
      "rank": 2
    },
    {
      "team": "Miami",
      "bcs_score": 0.827196,
      "computers": 0.75,
      "ap_pct": 0.896364,
      "coaches_pct": 0.835224,
      "comp_inputs_used": 4,
      "comp_rank": 7.2,
      "ap_rank": 2,
      "coaches_rank": 6,
      "rank": 3
    },
    {
      "team": "LSU",
      "bcs_score": 0.826311,
      "computers": 0.74,
      "ap_pct": 0.868485,
      "coaches_pct": 0.870448,
      "comp_inputs_used": 4,
      "comp_rank": 7.5,
      "ap_rank": 4,
      "coaches_rank": 4,
      "rank": 4
    },
    {
      "team": "Penn State",
      "bcs_score": 0.813805,
      "computers": 0.63,
      "ap_pct": 0.884848,
      "coaches_pct": 0.926567,
      "comp_inputs_used": 4,
      "comp_rank": 12,
      "ap_rank": 3,
      "coaches_rank": 2,
      "rank": 5
    },
    {
      "team": "Oregon",
      "bcs_score": 0.777268,
      "computers": 0.62,
      "ap_pct": 0.850909,
      "coaches_pct": 0.860896,
      "comp_inputs_used": 4,
      "comp_rank": 11.5,
      "ap_rank": 6,
      "coaches_rank": 5,
      "rank": 6
    },
    {
      "team": "Oklahoma",
      "bcs_score": 0.684993,
      "computers": 0.72,
      "ap_pct": 0.723636,
      "coaches_pct": 0.611343,
      "comp_inputs_used": 4,
      "comp_rank": 8,
      "ap_rank": 7,
      "coaches_rank": 10,
      "rank": 7
    },
    {
      "team": "Texas A&M",
      "bcs_score": 0.657461,
      "computers": 0.7,
      "ap_pct": 0.649697,
      "coaches_pct": 0.622687,
      "comp_inputs_used": 4,
      "comp_rank": 8.5,
      "ap_rank": 9,
      "coaches_rank": 9,
      "rank": 8
    },
    {
      "team": "Texas",
      "bcs_score": 0.650799,
      "computers": 0.59,
      "ap_pct": 0.640606,
      "coaches_pct": 0.721791,
      "comp_inputs_used": 4,
      "comp_rank": 18.5,
      "ap_rank": 10,
      "coaches_rank": 7,
      "rank": 9
    },
    {
      "team": "Ole Miss",
      "bcs_score": 0.648512,
      "computers": 0.84,
      "ap_pct": 0.510909,
      "coaches_pct": 0.594627,
      "comp_inputs_used": 4,
      "comp_rank": 5,
      "ap_rank": 13,
      "coaches_rank": 11,
      "rank": 10
    },
    {
      "team": "Indiana",
      "bcs_score": 0.605423,
      "computers": 0.67,
      "ap_pct": 0.6,
      "coaches_pct": 0.546269,
      "comp_inputs_used": 4,
      "comp_rank": 9.2,
      "ap_rank": 11,
      "coaches_rank": 12,
      "rank": 11
    },
    {
      "team": "Florida State",
      "bcs_score": 0.487895,
      "computers": 0.09,
      "ap_pct": 0.71697,
      "coaches_pct": 0.656716,
      "comp_inputs_used": 4,
      "comp_rank": 23.8,
      "ap_rank": 8,
      "coaches_rank": 8,
      "rank": 12
    },
    {
      "team": "Texas Tech",
      "bcs_score": 0.447062,
      "computers": 0.32,
      "ap_pct": 0.539394,
      "coaches_pct": 0.481791,
      "comp_inputs_used": 4,
      "comp_rank": 18,
      "ap_rank": 12,
      "coaches_rank": 14,
      "rank": 13
    },
    {
      "team": "Iowa State",
      "bcs_score": 0.427175,
      "computers": 0.29,
      "ap_pct": 0.472121,
      "coaches_pct": 0.519403,
      "comp_inputs_used": 4,
      "comp_rank": 21.5,
      "ap_rank": 14,
      "coaches_rank": 13,
      "rank": 14
    },
    {
      "team": "Alabama",
      "bcs_score": 0.399356,
      "computers": 0.45,
      "ap_pct": 0.360606,
      "coaches_pct": 0.387463,
      "comp_inputs_used": 4,
      "comp_rank": 18.8,
      "ap_rank": 17,
      "coaches_rank": 16,
      "rank": 15
    },
    {
      "team": "Tennessee",
      "bcs_score": 0.360571,
      "computers": 0.27,
      "ap_pct": 0.384848,
      "coaches_pct": 0.426866,
      "comp_inputs_used": 4,
      "comp_rank": 21.5,
      "ap_rank": 15,
      "coaches_rank": 15,
      "rank": 16
    },
    {
      "team": "Missouri",
      "bcs_score": 0.350816,
      "computers": 0.52,
      "ap_pct": 0.273939,
      "coaches_pct": 0.258507,
      "comp_inputs_used": 4,
      "comp_rank": 13,
      "ap_rank": 20,
      "coaches_rank": 19,
      "rank": 17
    },
    {
      "team": "Michigan",
      "bcs_score": 0.312525,
      "computers": 0.38,
      "ap_pct": 0.277576,
      "coaches_pct": 0.28,
      "comp_inputs_used": 4,
      "comp_rank": 16.5,
      "ap_rank": 19,
      "coaches_rank": 18,
      "rank": 18
    },
    {
      "team": "Georgia Tech",
      "bcs_score": 0.305186,
      "computers": 0.22,
      "ap_pct": 0.362424,
      "coaches_pct": 0.333134,
      "comp_inputs_used": 4,
      "comp_rank": 21.5,
      "ap_rank": 16,
      "coaches_rank": 17,
      "rank": 19
    },
    {
      "team": "USC",
      "bcs_score": 0.293997,
      "computers": 0.573333,
      "ap_pct": 0.16,
      "coaches_pct": 0.148657,
      "comp_inputs_used": 3,
      "comp_rank": 11.7,
      "ap_rank": 21,
      "coaches_rank": 22,
      "rank": 20
    },
    {
      "team": "Vanderbilt",
      "bcs_score": 0.259955,
      "computers": 0.2,
      "ap_pct": 0.330909,
      "coaches_pct": 0.248955,
      "comp_inputs_used": 4,
      "comp_rank": 21,
      "ap_rank": 18,
      "coaches_rank": 20,
      "rank": 21
    },
    {
      "team": "Notre Dame",
      "bcs_score": 0.192849,
      "computers": 0.29,
      "ap_pct": 0.132727,
      "coaches_pct": 0.155821,
      "comp_inputs_used": 4,
      "comp_rank": 31.5,
      "ap_rank": 22,
      "coaches_rank": 21,
      "rank": 22
    },
    {
      "team": "Illinois",
      "bcs_score": 0.105213,
      "computers": 0.1,
      "ap_pct": 0.087879,
      "coaches_pct": 0.127761,
      "comp_inputs_used": 4,
      "comp_rank": 31.2,
      "ap_rank": 23,
      "coaches_rank": 23,
      "rank": 23
    },
    {
      "team": "TCU",
      "bcs_score": 0.086834,
      "computers": 0.11,
      "ap_pct": 0.083636,
      "coaches_pct": 0.066866,
      "comp_inputs_used": 4,
      "comp_rank": 25.8,
      "ap_rank": 24,
      "coaches_rank": 25,
      "rank": 24
    },
    {
      "team": "BYU",
      "bcs_score": 0.083281,
      "computers": 0.06,
      "ap_pct": 0.079394,
      "coaches_pct": 0.110448,
      "comp_inputs_used": 4,
      "comp_rank": 28.5,
      "ap_rank": 25,
      "coaches_rank": 24,
      "rank": 25
    },
    {
      "team": "Mississippi State",
      "bcs_score": 0.07,
      "computers": 0.21,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 34,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 26
    },
    {
      "team": "Auburn",
      "bcs_score": 0.06,
      "computers": 0.18,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 25,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 27
    },
    {
      "team": "Memphis",
      "bcs_score": 0.046667,
      "computers": 0.14,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 32.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 28
    },
    {
      "team": "North Texas",
      "bcs_score": 0.043333,
      "computers": 0.13,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 47.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 29
    },
    {
      "team": "Washington",
      "bcs_score": 0.04,
      "computers": 0.12,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 27,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 30
    },
    {
      "team": "Houston",
      "bcs_score": 0.04,
      "computers": 0.12,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 37.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 31
    },
    {
      "team": "Louisville",
      "bcs_score": 0.036667,
      "computers": 0.11,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 25.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 32
    },
    {
      "team": "Maryland",
      "bcs_score": 0.033333,
      "computers": 0.1,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 40,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 33
    },
    {
      "team": "Arizona State",
      "bcs_score": 0.033333,
      "computers": 0.1,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 25.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 34
    },
    {
      "team": "Florida",
      "bcs_score": 0.03,
      "computers": 0.09,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 50.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 35
    },
    {
      "team": "UCF",
      "bcs_score": 0.016667,
      "computers": 0.05,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 46.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 36
    },
    {
      "team": "Clemson",
      "bcs_score": 0.006667,
      "computers": 0.02,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 55,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 37
    },
    {
      "team": "South Florida",
      "bcs_score": 0.003333,
      "computers": 0.01,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 43.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 38
    },
    {
      "team": "Wyoming",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 100.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 39
    },
    {
      "team": "Wisconsin",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 62.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 40
    },
    {
      "team": "Western Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 109.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 41
    },
    {
      "team": "Western Kentucky",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 88.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 42
    },
    {
      "team": "West Virginia",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 67.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 43
    },
    {
      "team": "West Kentucky",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 80.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 44
    },
    {
      "team": "Washington State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 105,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 45
    },
    {
      "team": "Washington St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 74,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 46
    },
    {
      "team": "Wake Forest",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 84.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 47
    },
    {
      "team": "W Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 103,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 48
    },
    {
      "team": "Virginia Tech",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 84.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 49
    },
    {
      "team": "Virginia",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 53.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 50
    },
    {
      "team": "Utah State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 95.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 51
    },
    {
      "team": "Utah St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 65.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 52
    },
    {
      "team": "Utah",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 37,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 53
    },
    {
      "team": "UTSA",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 74.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 54
    },
    {
      "team": "UTEP",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "comp_rank": 126.7,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 55
    },
    {
      "team": "UNLV",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "comp_rank": 55,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 56
    },
    {
      "team": "UCLA",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 97.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 57
    },
    {
      "team": "UAB",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 116.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 58
    },
    {
      "team": "Tulsa",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 120.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 59
    },
    {
      "team": "Tulane",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 46.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 60
    },
    {
      "team": "Troy",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 91.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 61
    },
    {
      "team": "Toledo",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 81.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 62
    },
    {
      "team": "Texas-El Paso",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 130,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 63
    },
    {
      "team": "Texas State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 66.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 64
    },
    {
      "team": "Texas St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 58,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 65
    },
    {
      "team": "Temple",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 107,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 66
    },
    {
      "team": "Syracuse",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 39,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 67
    },
    {
      "team": "Stanford",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 92.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 68
    },
    {
      "team": "Southern Miss",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 105,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 69
    },
    {
      "team": "Southern Cal",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 27,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 70
    },
    {
      "team": "South Carolina",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 44.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 71
    },
    {
      "team": "South Alabama",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 108.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 72
    },
    {
      "team": "San Jose State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 98,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 73
    },
    {
      "team": "San Jose St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 112,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 74
    },
    {
      "team": "San Diego State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 106,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 75
    },
    {
      "team": "San Diego St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 73.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 76
    },
    {
      "team": "Sam Houston State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 175,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 77
    },
    {
      "team": "Sam Houston St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 141.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 78
    },
    {
      "team": "Sam Houston",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 83,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 79
    },
    {
      "team": "SMU",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 52.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 80
    },
    {
      "team": "Rutgers",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 56.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 81
    },
    {
      "team": "Rice",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 96,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 82
    },
    {
      "team": "Purdue",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 89.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 83
    },
    {
      "team": "Pitt",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 60.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 84
    },
    {
      "team": "Oregon State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 91.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 85
    },
    {
      "team": "Oregon St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 117.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 86
    },
    {
      "team": "Old Dominion",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 68.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 87
    },
    {
      "team": "Oklahoma State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "comp_rank": 100.3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 88
    },
    {
      "team": "Oklahoma St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 117,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 89
    },
    {
      "team": "Ohio",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 73,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 90
    },
    {
      "team": "Northwestern",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 85.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 91
    },
    {
      "team": "Northern Illinois",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 110.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 92
    },
    {
      "team": "North Carolina St.",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 46,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 93
    },
    {
      "team": "North Carolina",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 74.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 94
    },
    {
      "team": "New Mexico State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 158.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 95
    },
    {
      "team": "New Mexico St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 90,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 96
    },
    {
      "team": "New Mexico",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 92.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 97
    },
    {
      "team": "Nevada-Las Vegas",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 47,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 98
    },
    {
      "team": "Nevada",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 135.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 99
    },
    {
      "team": "Nebraska",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 33.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 100
    },
    {
      "team": "Navy",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 50.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 101
    },
    {
      "team": "NC State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "comp_rank": 43.7,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 102
    },
    {
      "team": "Missouri State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 118,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 103
    },
    {
      "team": "Missouri St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 96.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 104
    },
    {
      "team": "Minnesota",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 57.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 105
    },
    {
      "team": "Middle Tennessee",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 156,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 106
    },
    {
      "team": "Middle Tenn St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 133.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 107
    },
    {
      "team": "Michigan State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "comp_rank": 53.3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 108
    },
    {
      "team": "Michigan St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 47,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 109
    },
    {
      "team": "Miami-Ohio",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 108,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 110
    },
    {
      "team": "Miami (Ohio)",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 88,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 111
    },
    {
      "team": "Miami (OH)",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 125,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 112
    },
    {
      "team": "Massachusetts",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 160.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 113
    },
    {
      "team": "Marshall",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 103.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 114
    },
    {
      "team": "Louisiana Tech",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 83,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 115
    },
    {
      "team": "Louisiana",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 109,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 116
    },
    {
      "team": "Liberty",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 118,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 117
    },
    {
      "team": "La. Monroe",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 105,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 118
    },
    {
      "team": "La. Lafayette",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 113,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 119
    },
    {
      "team": "LA Monroe",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "comp_rank": 106,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 120
    },
    {
      "team": "LA Lafayette",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 122,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 121
    },
    {
      "team": "Kentucky",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 50.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 122
    },
    {
      "team": "Kent State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 185,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 123
    },
    {
      "team": "Kent St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 127.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 124
    },
    {
      "team": "Kennesaw State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 123.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 125
    },
    {
      "team": "Kansas State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "comp_rank": 58,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 126
    },
    {
      "team": "Kansas St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 119,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 127
    },
    {
      "team": "Kansas",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 36.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 128
    },
    {
      "team": "James Madison",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 65,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 129
    },
    {
      "team": "Jacksonville State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 94,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 130
    },
    {
      "team": "Jacksonville St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 98,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 131
    },
    {
      "team": "Iowa",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 37,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 132
    },
    {
      "team": "Hawaii",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 89.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 133
    },
    {
      "team": "Georgia State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 139,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 134
    },
    {
      "team": "Georgia St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 115,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 135
    },
    {
      "team": "Georgia Southern",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 88,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 136
    },
    {
      "team": "Fresno State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 75.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 137
    },
    {
      "team": "Fresno St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 50.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 138
    },
    {
      "team": "Florida Intl",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 118,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 139
    },
    {
      "team": "Florida Atlantic",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 126.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 140
    },
    {
      "team": "FCS GROUP 9",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 164,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 141
    },
    {
      "team": "FCS GROUP 8",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 153,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 142
    },
    {
      "team": "FCS GROUP 7",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 131,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 143
    },
    {
      "team": "FCS GROUP 6",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 162,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 144
    },
    {
      "team": "FCS GROUP 5",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 143,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 145
    },
    {
      "team": "FCS GROUP 4",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 134,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 146
    },
    {
      "team": "FCS GROUP 31",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 167,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 147
    },
    {
      "team": "FCS GROUP 30",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 142,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 148
    },
    {
      "team": "FCS GROUP 3",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 155,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 149
    },
    {
      "team": "FCS GROUP 29",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 161,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 150
    },
    {
      "team": "FCS GROUP 28",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 146,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 151
    },
    {
      "team": "FCS GROUP 27",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 160,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 152
    },
    {
      "team": "FCS GROUP 26",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 135,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 153
    },
    {
      "team": "FCS GROUP 25",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 140,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 154
    },
    {
      "team": "FCS GROUP 24",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 147,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 155
    },
    {
      "team": "FCS GROUP 23",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 145,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 156
    },
    {
      "team": "FCS GROUP 22",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 152,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 157
    },
    {
      "team": "FCS GROUP 21",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 156,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 158
    },
    {
      "team": "FCS GROUP 20",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 157,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 159
    },
    {
      "team": "FCS GROUP 2",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 112,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 160
    },
    {
      "team": "FCS GROUP 19",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 165,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 161
    },
    {
      "team": "FCS GROUP 18",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 123,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 162
    },
    {
      "team": "FCS GROUP 17",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 166,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 163
    },
    {
      "team": "FCS GROUP 16",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 163,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 164
    },
    {
      "team": "FCS GROUP 15",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 150,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 165
    },
    {
      "team": "FCS GROUP 14",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 110,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 166
    },
    {
      "team": "FCS GROUP 13",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 138,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 167
    },
    {
      "team": "FCS GROUP 12",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 148,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 168
    },
    {
      "team": "FCS GROUP 11",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 151,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 169
    },
    {
      "team": "FCS GROUP 10",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 144,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 170
    },
    {
      "team": "FCS GROUP 1",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 1,
      "comp_rank": 158,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 171
    },
    {
      "team": "Eastern Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 130.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 172
    },
    {
      "team": "East Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 130.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 173
    },
    {
      "team": "East Carolina",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 80.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 174
    },
    {
      "team": "Duke",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 59.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 175
    },
    {
      "team": "Delaware",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 3,
      "comp_rank": 92.3,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 176
    },
    {
      "team": "Connecticut",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 98.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 177
    },
    {
      "team": "Colorado State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 91.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 178
    },
    {
      "team": "Colorado St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 112,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 179
    },
    {
      "team": "Colorado",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 58.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 180
    },
    {
      "team": "Coastal Carolina",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 107.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 181
    },
    {
      "team": "Cincinnati",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 55.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 182
    },
    {
      "team": "Charlotte",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 144.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 183
    },
    {
      "team": "Central Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 111.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 184
    },
    {
      "team": "Cent Michigan",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 104.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 185
    },
    {
      "team": "California",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 65.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 186
    },
    {
      "team": "Buffalo",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 106.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 187
    },
    {
      "team": "Bowling Green",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 92.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 188
    },
    {
      "team": "Boston College",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 68,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 189
    },
    {
      "team": "Boston Coll",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 101.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 190
    },
    {
      "team": "Boise State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 47,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 191
    },
    {
      "team": "Boise St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 60.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 192
    },
    {
      "team": "Baylor",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 51.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 193
    },
    {
      "team": "Ball State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 144,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 194
    },
    {
      "team": "Ball St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 130,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 195
    },
    {
      "team": "Army",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 82.2,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 196
    },
    {
      "team": "Arkansas State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 115,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 197
    },
    {
      "team": "Arkansas St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 126,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 198
    },
    {
      "team": "Arkansas",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 44.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 199
    },
    {
      "team": "Arizona St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 29.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 200
    },
    {
      "team": "Arizona",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 46.8,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 201
    },
    {
      "team": "Appalachian State",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 126,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 202
    },
    {
      "team": "Appalachian St",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 2,
      "comp_rank": 93.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 203
    },
    {
      "team": "Akron",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 139.5,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 204
    },
    {
      "team": "Air Force",
      "bcs_score": 0.0,
      "computers": 0.0,
      "ap_pct": 0.0,
      "coaches_pct": 0.0,
      "comp_inputs_used": 4,
      "comp_rank": 108,
      "ap_rank": null,
      "coaches_rank": null,
      "rank": 205
    }
  ],
  "build_time": "2025-09-23T02:25:54Z",
  "source_week": "data/2025/week05"
};