"""Canonical team name helpers."""

ALIAS = {
  "Miami (FL)": "Miami",
  "Miami (Fla.)": "Miami",
  "Texas-San Antonio": "UTSA",
  "Texas A&M": "Texas A&M",
  "Mississippi": "Ole Miss",
  "Southern California": "USC",
  "Central Florida": "UCF",
  "Brigham Young": "BYU",
  "Louisiana State": "LSU",
  "Pittsburgh": "Pitt",
  "Texas Christian": "TCU",
  # Coaches poll variants with suffixes
  "Ohio State OhioSt": "Ohio State",
  "Penn State PSU": "Penn State",
  "Georgia UGa": "Georgia",
  "LSU LSU": "LSU",
  "Oregon ORE": "Oregon",
  "Miami (FL) MIA-FL": "Miami",
  "Texas Tex": "Texas",
  "Florida State FSU": "Florida State",
  "Texas A&M TexA&M": "Texas A&M",
  "Oklahoma Okla": "Oklahoma",
  "Ole Miss Miss": "Ole Miss",
  "Indiana IU": "Indiana",
  "Iowa State IaSt": "Iowa State",
  "Texas Tech TTU": "Texas Tech",
  "Tennessee Tenn": "Tennessee",
  "Alabama BAMA": "Alabama",
  "Georgia Tech GT": "Georgia Tech",
  "Michigan Mich": "Michigan",
  "Missouri MIZZOU": "Missouri",
  "Vanderbilt Vandy": "Vanderbilt",
  "Notre Dame ND": "Notre Dame",
  "USC USC": "USC",
  "Illinois Ill": "Illinois",
  "BYU BYU": "BYU",
  "TCU TCU": "TCU",
  # AP poll variants
  "Southern Cal.": "USC",
  # Colley variants
  "Ohio St": "Ohio State",
  "Penn St": "Penn State",
  "Florida St": "Florida State",
  "Iowa St": "Iowa State",
  "Mississippi St": "Mississippi State",
  # Massey variants (with conference info)
  "Ohio St Big 10": "Ohio State",
  "Penn St Big 10": "Penn State",
  "Florida St Atlantic Coast": "Florida State",
  "Iowa St Big 12": "Iowa State",
  "Mississippi St Southeastern": "Mississippi State",
  "Georgia Southeastern": "Georgia",
  "Mississippi Southeastern": "Ole Miss",
  "Oregon Big 10": "Oregon",
  "Texas Southeastern": "Texas",
  "Oklahoma Southeastern": "Oklahoma",
  "Texas A&M Southeastern": "Texas A&M",
  "Indiana Big 10": "Indiana",
  "LSU Southeastern": "LSU",
  "Alabama Southeastern": "Alabama",
  "Miami FL Atlantic Coast": "Miami",
  "Missouri Southeastern": "Missouri",
  "USC Big 10": "USC",
  "Tennessee Southeastern": "Tennessee",
  "Michigan Big 10": "Michigan",
  "TCU Big 12": "TCU",
  "Texas Tech Big 12": "Texas Tech",
  "BYU Big 12": "BYU",
  "Vanderbilt Southeastern": "Vanderbilt",
  "Notre Dame FBS Indep": "Notre Dame",
  "Washington Big 10": "Washington",
  "Auburn Southeastern": "Auburn",
  "Louisville Atlantic Coast": "Louisville",
  "Georgia Tech Atlantic Coast": "Georgia Tech",
  "Iowa Big 10": "Iowa",
  "Nebraska Big 10": "Nebraska",
  "Utah Big 12": "Utah",
  "Arizona St Big 12": "Arizona St",
  "Maryland Big 10": "Maryland",
  "Memphis American Athletic": "Memphis",
  "Kansas Big 12": "Kansas",
  "UCF Big 12": "UCF",
  "Arizona Big 12": "Arizona",
  "Illinois Big 10": "Illinois",
  "Houston Big 12": "Houston",
  "Arkansas Southeastern": "Arkansas",
  "South Carolina Southeastern": "South Carolina",
  "Kentucky Southeastern": "Kentucky",
  "Tulane American Athletic": "Tulane",
  "Syracuse Atlantic Coast": "Syracuse",
  "Baylor Big 12": "Baylor",
  "UNLV Mountain West": "UNLV",
  "North Texas American Athletic": "North Texas",
  "Florida Southeastern": "Florida",
  "NC State Atlantic Coast": "NC State",
  "Wisconsin Big 10": "Wisconsin",
  "Rutgers Big 10": "Rutgers",
  "SMU Atlantic Coast": "SMU",
  "South Florida American Athletic": "South Florida",
  "Cincinnati Big 12": "Cincinnati",
  "Michigan St Big 10": "Michigan State",
  "Minnesota Big 10": "Minnesota",
  "Navy American Athletic": "Navy",
  "Clemson Atlantic Coast": "Clemson",
  "Boise St Mountain West": "Boise St",
  "California Atlantic Coast": "California",
  "Virginia Atlantic Coast": "Virginia",
  "Kansas St Big 12": "Kansas State",
  "Colorado Big 12": "Colorado",
  "Fresno St Mountain West": "Fresno St",
  "West Virginia Big 12": "West Virginia",
  "Pittsburgh Atlantic Coast": "Pitt",
  "James Madison Sun Belt": "James Madison",
  "Old Dominion Sun Belt": "Old Dominion",
  "Duke Atlantic Coast": "Duke",
  "Texas St Sun Belt": "Texas St",
  "Ohio Mid-American": "Ohio",
  "Purdue Big 10": "Purdue",
  "North Carolina Atlantic Coast": "North Carolina",
  "East Carolina American Athletic": "East Carolina",
  "Northwestern Big 10": "Northwestern",
  "Army American Athletic": "Army",
  "UT San Antonio American Athletic": "UTSA",
  "Utah St Mountain West": "Utah St",
  "Boston College Atlantic Coast": "Boston Coll",
  "Washington St Pac 12": "Washington St",
  "Virginia Tech Atlantic Coast": "Virginia Tech",
  "New Mexico Mountain West": "New Mexico",
  "WKU Conference USA": "West Kentucky",
  "Toledo Mid-American": "Toledo",
  "Oklahoma St Big 12": "Oklahoma State",
  "San Diego St Mountain West": "San Diego St",
  "Wake Forest Atlantic Coast": "Wake Forest",
  "UCLA Big 10": "UCLA",
  "Troy Sun Belt": "Troy",
  "Louisiana Tech Conference USA": "Louisiana Tech",
  "Stanford Atlantic Coast": "Stanford",
  "Rice American Athletic": "Rice",
  "Wyoming Mountain West": "Wyoming",
  "Marshall Sun Belt": "Marshall",
  "Bowling Green Mid-American": "Bowling Green",
  "Jacksonville St Conference USA": "Jacksonville St",
  "Hawaii Mountain West": "Hawaii",
  "Ga Southern Sun Belt": "Georgia Southern",
  "Coastal Car Sun Belt": "Coastal Carolina",
  "W Michigan Mid-American": "W Michigan",
  "Miami OH Mid-American": "Miami (OH)",
  "Air Force Mountain West": "Air Force",
  "N Illinois Mid-American": "Northern Illinois",
  "Missouri St Conference USA": "Missouri St",
  "Oregon St Pac 12": "Oregon St",
  "San Jose St Mountain West": "San Jose St",
  "Tulsa American Athletic": "Tulsa",
  "Connecticut FBS Indep": "Connecticut",
  "Delaware Conference USA": "Delaware",
  "Colorado St Mountain West": "Colorado St",
  "South Alabama Sun Belt": "South Alabama",
  "Temple American Athletic": "Temple",
  "Appalachian St Sun Belt": "Appalachian St",
  "UAB American Athletic": "UAB",
  "C Michigan Mid-American": "Cent Michigan",
  "Buffalo Mid-American": "Buffalo",
  "ULM Sun Belt": "LA Monroe",
  "Liberty Conference USA": "Liberty",
  "Louisiana Sun Belt": "LA Lafayette",
  "Southern Miss Sun Belt": "Southern Miss",
  "Nevada Mountain West": "Nevada",
  "New Mexico St Conference USA": "New Mexico St",
  "FL Atlantic American Athletic": "Florida Atlantic",
  "Florida Intl Conference USA": "Florida Intl",
  "Arkansas St Sun Belt": "Arkansas St",
  "Georgia St Sun Belt": "Georgia St",
  "UTEP Conference USA": "UTEP",
  "Ball St Mid-American": "Ball St",
  "Sam Houston St Conference USA": "Sam Houston St",
  "MTSU Conference USA": "Middle Tenn St",
  "Charlotte American Athletic": "Charlotte",
  "Kennesaw Conference USA": "Kennesaw State",
  "E Michigan Mid-American": "East Michigan",
  "Akron Mid-American": "Akron",
      "Kent Mid-American": "Kent St",
      "Massachusetts Mid-American": "Massachusetts",
      # Sagarin variants
      "Miami-Florida": "Miami",
      "Central Florida(UCF)": "UCF",
      "LouisianaMonroe(ULM)": "LA Monroe",
      "Army West Point": "Army",
      "Fla. International": "Florida Intl",
      "Hawai'i": "Hawaii",
      "Louisiana-Lafayette": "Louisiana",
      # add as you encounter variants...
}

def canon(name: str) -> str:
    n = name.strip()
    return ALIAS.get(n, n)


